include:
    -   template: Security/Dependency-Scanning.gitlab-ci.yml
    -   template: SAST.gitlab-ci.yml
    -   template: Secret-Detection.gitlab-ci.yml

stages:
    - test
    - announce

.job_template: &test_job
    stage: test
    script:
        - phing test
    cache:
        paths:
            - vendor/

test:php8.3:
    <<: *test_job
    image: nexendrie/php:8.3

test:reports:
    <<: *test_job
    image: nexendrie/php:8.3
    variables:
        REPORTS: 1
    coverage: '/(\d+\%) covered/'
    artifacts:
        reports:
            coverage_report:
                coverage_format: cobertura
                path: coverage.xml
            junit: junit.xml

sast:
    variables:
        SAST_DEFAULT_ANALYZERS: "phpcs-security-audit"

announce:gitlab:
    stage: announce
    image: registry.gitlab.com/gitlab-org/release-cli:latest
    only:
        - tags@konecnyjakub/mytester
    script:
        - echo "Creating GitLab release"
    release:
        tag_name: $CI_COMMIT_TAG
        name: "My Tester $CI_COMMIT_TAG"
        description: "./RELEASE_NOTES"
