include:
  - template: Security/Dependency-Scanning.gitlab-ci.yml
  - template: License-Scanning.gitlab-ci.yml
  - template: SAST.gitlab-ci.yml
  - template: Secret-Detection.gitlab-ci.yml

image: nexendrie/php:8.0

stages:
  - test

cache:
  paths:
  - vendor/

.job_template: &test_job
  stage: test
  script:
  - phing test

test:php8.0:
  <<: *test_job
  image: nexendrie/php:8.0

test:php8.1:
  <<: *test_job
  image: nexendrie/php:8.1
  coverage: '/(\d+\%) covered/'

sast:
  variables:
    SAST_DEFAULT_ANALYZERS: "phpcs-security-audit"
