build:
    environment:
        php:
            version: 8.3.3
        postgresql: false
        redis: false
        rabbitmq: false
    nodes:
        tests:
            cache:
                directories:
                    - vendor/
            environment:
                variables:
                    XDEBUG_MODE: 'coverage'
            tests:
                override:
                    -
                        command: ./vendor/bin/phpcs . --extensions=php --report=checkstyle --report-file=codesniffer.xml --standard=phpcs.xml
                        analysis:
                            file: codesniffer.xml
                            format: 'general-checkstyle'
                    -
                        command: ./vendor/bin/phpstan analyze --error-format=checkstyle | tee phpstan.xml
                        analysis:
                            file: phpstan.xml
                            format: 'general-checkstyle'
                    - php ./tests/NetteDI.php
                    -
                        command: php ./tests/NetteDI.php
                        coverage:
                            file: coverage.xml
                            format: 'cobertura'
