language: php

php:
    - 7.0
    - 7.1

notifications:
    email: false

env:
    - PHP_BIN=php
    - PHP_BIN=php-cgi
    
before_install:
    - if [ "$TRAVIS_PHP_VERSION" != "7.1" ]; then phpenv config-rm xdebug.ini; fi
    - composer self-update

install:
    - composer install --no-interaction --prefer-dist
  
script:
    - if [ "$PHP_BIN" = "php" ]; then ./vendor/bin/parallel-lint src tests -e php,phpt; fi
    - if [ "$PHP_BIN" = "php" ]; then ./vendor/bin/phpcs --extensions=php,phpt . --standard=ruleset.xml --colors; fi
    - $PHP_BIN ./src/mytester
    - $PHP_BIN ./tests/NetteDI.php

cache:
    directories:
        - $HOME/.composer/cache
        - vendor
