language: php

php:
    - 7.1
    - nightly

notifications:
    email: false

env:
    - PHP_BIN=php
    - PHP_BIN=php-cgi

matrix:
    allow_failures:
        - php: nightly

before_install:
    - composer self-update

install:
    - composer install --no-interaction --prefer-dist
  
script:
    - ./vendor/bin/parallel-lint src tests -e php,phpt
    - ./vendor/bin/phpcs --extensions=php,phpt . --standard=ruleset.xml --colors
    - ./vendor/bin/phpstan analyze -l 5 -c phpstan.neon src tests
    - $PHP_BIN ./src/mytester
    - $PHP_BIN ./tests/NetteDI.php

cache:
    directories:
        - $HOME/.composer/cache
        - vendor
