language: php

php:
    - '7.2'
    - '7.3'
    - 7.4snapshot
    - nightly

notifications:
    email: false

env:
    - PHP_BIN=php
    - PHP_BIN=php-cgi

matrix:
    fast_finish: true
    allow_failures:
        - php: nightly
        - php: 7.4snapshot

before_install:
    - composer self-update

install:
    - wget https://www.phing.info/get/phing-latest.phar && mv phing-latest.phar phing && chmod +x phing
  
script:
    - ./phing -Dbinary=$PHP_BIN

cache:
    directories:
        - $HOME/.composer/cache
        - vendor
