language: php

php:
    - 5.6
    - 7.0
    - 7.1
    - nightly

notifications:
    email: false

env:
    - PHP_BIN=php
    - PHP_BIN=php-cgi

matrix:
    allow_failures:
        - php: nightly

before_install:
    - if [ "$TRAVIS_PHP_VERSION" != "7.1" ]; then phpenv config-rm xdebug.ini; fi
    - composer self-update

install:
    - wget https://www.phing.info/get/phing-latest.phar && mv phing-latest.phar phing && chmod +x phing
  
script:
    - ./phing -Dbinary=$PHP_BIN

cache:
    directories:
        - $HOME/.composer/cache
        - vendor
