language: php

php:
    - '7.4'
    - '8.0'
    - nightly

notifications:
    email: false

matrix:
    fast_finish: true
    allow_failures:
        - php: nightly

before_install:
    - composer self-update --2

install:
    - wget https://www.phing.info/get/phing-latest.phar && mv phing-latest.phar phing && chmod +x phing
  
script:
    - ./phing

cache:
    directories:
        - $HOME/.composer/cache
        - vendor
