language: php

php:
    - 7.1

notifications:
    email: false

env:
    - PHP_BIN=php
    - PHP_BIN=php-cgi
    
before_install:
    - composer self-update

install:
    - composer install --no-interaction --prefer-dist
  
script:
    - if [ "$PHP_BIN" = "php" ]; then ./vendor/bin/parallel-lint src tests -e php,phpt; fi
    - if [ "$PHP_BIN" = "php" ]; then ./vendor/bin/phpcs --extensions=php,phpt . --standard=ruleset.xml --colors; fi
    - if [ "$PHP_BIN" = "php" ]; then ./vendor/bin/phpstan analyze -l 5 -c phpstan.neon src tests; fi
    - $PHP_BIN ./src/mytester
    - $PHP_BIN ./tests/NetteDI.php

cache:
    directories:
        - $HOME/.composer/cache
        - vendor
