language: php

php:
    - 5.6
    - 7.0
    - 7.1

notifications:
    email: false

env:
    - PHP_BIN=php
    - PHP_BIN=php-cgi
    
before_install:
    - composer self-update

install:
    - composer install --no-interaction --prefer-dist
  
script:
    - $PHP_BIN ./mytester.php

cache:
    directories:
        - $HOME/.composer/cache
        - vendor
