#!/usr/bin/env php
<?php
require_once __DIR__ . "/functions.php";

require findVendorDirectory() . "/autoload.php";

$testsDir = getTestsDirectory();
$tester = new MyTester\Tester($testsDir);
$tester->execute();
?>